Roll back a place where StandardSystemProperty doesn't work.
java.lang.NoClassDefFoundError: com/google/common/base/StandardSystemProperty
	at ratpack.gradle.SpringloadedUtil.getSpringLoadedConfig(SpringloadedUtil.groovy:56)
	at ratpack.gradle.SpringloadedUtil.this$2$getSpringLoadedConfig(SpringloadedUtil.groovy)
	at ratpack.gradle.SpringloadedUtil.getSpringloadedJvmArgs(SpringloadedUtil.groovy:47)
	at ratpack.gradle.RatpackPlugin$_apply_closure4_closure11.doCall(RatpackPlugin.groovy:61)
	at ratpack.gradle.RatpackPlugin$_apply_closure4.doCall(RatpackPlugin.groovy:59)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:548)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:529)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 47 more
Caused by: java.lang.ClassNotFoundException: com.google.common.base.StandardSystemProperty
	... 56 more